apiVersion: v1
kind: Service
metadata:
  name: fpa-abc
spec:
  # type: LoadBalancer
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30081
  selector:
    app: fpa-abc-app 